prefix=${CMAKE_INSTALL_PREFIX}
includedir=${PKG_CONFIG_INCLUDEDIR}
libdir=${PKG_CONFIG_LIBDIR}

Name: ${PROJECT_NAME}
Description: ${PROJECT_DESCRIPTION}
Version: ${LIBRARY_VERSION}
Requires: ${PKG_CONFIG_REQUIRES}
Libs: ${PKG_CONFIG_LIBS}
Cflags: ${PKG_CONFIG_CFLAGS}
